
name: armtemplatedeploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group githubactions-rg
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: deefdd30-bfc7-4245-a3b2-f6141b537894
          region: West Europe
          template: ./arm-template/resourcegroup.json
          deploymentName: githubactions-rg