name: armtemplatedeploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
# Login in Azure
      - name: Azure Login
        uses: Azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  
# Create Resource Group 
      - name: Deploy Resource Group githubactions-rg
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: deefdd30-bfc7-4245-a3b2-f6141b537894
          region: West Europe
          template: ./arm-template/resourcegroup.json
          deploymentName: githubactions-rg

#Create StorageAccount with Parameters
      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: githubactions-rg
          subscriptionId: deefdd30-bfc7-4245-a3b2-f6141b537894
          template: ./arm-template/storageaccount.json
          parameters: ./arm-template/storageaccount.parameters.json
          deploymentMode: incremental

#Create Workspace
      - name: Deploy Workspace
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: githubactions-rg
          subscriptionId: deefdd30-bfc7-4245-a3b2-f6141b537894
          template: ./arm-template/workspace.json
          parameters: ./arm-template/workspace-parameters.json
          deploymentMode: incremental

#Create Host Pool
      - name: Deploy Host Pool
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: githubactions-rg
          subscriptionId: deefdd30-bfc7-4245-a3b2-f6141b537894
          template: ./arm-template/hostpool.json
          parameters: ./arm-template/hostpool-parameters.json
          deploymentMode: incremental
